### ISSUE TITLE
Type Error in FFT.cpp

### ISSUE THREAD

**Issue by andrewb1234** [cannam/constant-q-cpp#2]
ri is defined to be pointer to a double, but all of the kiss_fft function definitions take it as a float. Incompatible type error.

**Comment by cannam** [comment]
For this reason we have `-Dkiss_fft_scalar=double` at [line 19 of Makefile.inc](https://github.com/cannam/constant-q-cpp/blob/bedf13ba505b813a957374da01df41584a9ae983/Makefile.inc#L19) which redefines the type in the KissFFT code.

I've added a note about this to the README, which has been seriously lacking in any information about how to build the thing (sorry). It still isn't all that helpful but it's better than it was.
